# Site settings
title: 竹星梦华
description: Jekyll Theme Minimal Resume

# User settings
username: 竹星梦华
user_description: I'm a Software Engineer from China.
user_title: Software Engineer
email: 3021208079@tju.edu.cn

exclude: ['package.json', 'src' , 'node_modules']
