# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 竹星梦华
user_description: I'm a Software Engineer from China.
user_title: Software Engineer
email: 3021208079@tju.edu.cn

exclude: ['package.json', 'src' , 'node_modules']
